import { db } from '@/lib/db';
import { CATEGORIES } from '@/lib/constants';

const SEED_USERS = [
  { id: 'user_1', email: 'sarah@techventures.com', name: 'Sarah Mitchell', role: 'seller', company: 'TechVentures Inc.', country: 'United States', city: 'San Francisco', verified: true },
  { id: 'user_2', email: 'james@globalinvest.com', name: 'James Chen', role: 'investor', company: 'Global Invest Partners', country: 'United Kingdom', city: 'London', verified: true },
  { id: 'user_3', email: 'amina@digitalhub.ae', name: 'Amina Al-Rashid', role: 'seller', company: 'Digital Hub LLC', country: 'UAE', city: 'Dubai', verified: true },
  { id: 'user_4', email: 'raj@indiatech.in', name: 'Raj Patel', role: 'seller', company: 'IndiaTech Solutions', country: 'India', city: 'Bangalore', verified: true },
  { id: 'user_5', email: 'lisa@propmart.com', name: 'Lisa Thompson', role: 'broker', company: 'PropMart International', country: 'Canada', city: 'Toronto', verified: true },
  { id: 'user_6', email: 'carlos@latamfund.com', name: 'Carlos Rodriguez', role: 'investor', company: 'LatAm Fund', country: 'Brazil', city: 'São Paulo', verified: true },
];

const SEED_PROJECTS = [
  {
    id: 'proj_1', name: 'CloudSync Pro', category: 'saas', industry: 'Technology', country: 'United States', city: 'San Francisco',
    businessStage: 'growth', foundedYear: 2021, status: 'active', visibility: 'public', featured: true,
    overview: 'CloudSync Pro is a comprehensive cloud file synchronization platform serving over 50,000 businesses worldwide. The platform offers real-time file sync, collaboration tools, enterprise-grade security, and seamless integration with 200+ business applications.',
    businessModel: 'B2B SaaS subscription with tiered pricing plans. Free tier for individuals, Pro plan at $29/user/month, Enterprise at $99/user/month with custom features.',
    targetMarket: 'Small to medium businesses (SMBs), remote teams, and enterprise organizations requiring secure file collaboration.',
    revenueModel: 'Monthly/Annual SaaS subscriptions. Additional revenue from storage add-ons, premium support, and API access.',
    growthOpportunity: 'Expanding into Asia-Pacific market. AI-powered file organization feature in development. Partnership pipeline with major ERP providers.',
    competitiveAdvantage: 'Proprietary delta-sync technology reducing bandwidth usage by 80%. Military-grade AES-256 encryption. Zero-knowledge architecture.',
    businessRisks: 'Increasing competition from major players. Data regulation changes across jurisdictions. Dependency on cloud infrastructure costs.',
    exitOpportunities: 'Acquisition target for larger SaaS conglomerates. Potential IPO within 3-5 years. Strategic partnership with major tech companies.',
    developmentCost: 450000, infrastructureCost: 120000, marketingCost: 200000, legalCost: 50000, operationalCost: 180000, technologyCost: 95000, maintenanceCost: 60000,
    totalInvestment: 1155000, expectedROI: 340, monthlyRevenue: 185000, annualRevenue: 2220000, netProfit: 890000, ebitda: 1120000,
    breakEvenAnalysis: 'Achieved break-even in month 14. Current run rate shows 3.4x ROI annually.',
    companyValuation: 18500000, suggestedSellingPrice: 22000000, reservePrice: 18000000, minimumOffer: 15000000, buyNowPrice: 25000000,
    websiteUrl: 'https://cloudsyncpro.com', demoUrl: 'https://demo.cloudsyncpro.com', technologyStack: 'React, Node.js, PostgreSQL, Redis, AWS, Kubernetes',
    hostingProvider: 'AWS', cloudInfrastructure: 'Kubernetes on AWS EKS', sourceCodeAvailable: true,
    monthlyVisitors: 850000, monthlyActiveUsers: 52000, registeredUsers: 125000, customers: 50000, subscribers: 32000, conversionRate: 6.2, seoScore: 87,
    aiValuation: 19200000, investorPrice: 17000000, wholesalePrice: 15500000, acquisitionPrice: 22000000,
    tags: 'saas,cloud,enterprise,productivity,file-sync,collaboration',
    sellerId: 'user_1', images: '', thumbnail: '',
  },
  {
    id: 'proj_2', name: 'MediConnect AI', category: 'ai-solutions', industry: 'Healthcare', country: 'UAE', city: 'Dubai',
    businessStage: 'startup', foundedYear: 2023, status: 'active', visibility: 'public', featured: true,
    overview: 'MediConnect AI is an AI-powered telemedicine and diagnostic platform that connects patients with healthcare providers across the Middle East. Features include AI-assisted diagnosis, virtual consultations, prescription management, and integration with hospital systems.',
    businessModel: 'B2B2C model. Partner hospitals pay licensing fees. Patients pay per-consultation fees. Premium subscription for unlimited access.',
    targetMarket: 'Healthcare providers, hospitals, clinics, and patients across the Middle East and North Africa region.',
    revenueModel: 'Hospital licensing ($5,000-50,000/month), patient consultation fees ($25-75), premium subscriptions ($49/month).',
    growthOpportunity: 'Expansion to Southeast Asia. FDA approval pathway for AI diagnostics. Insurance company partnerships.',
    competitiveAdvantage: 'Multilingual AI supporting Arabic, English, Hindi, and Urdu. First-mover in MENA telemedicine AI space.',
    businessRisks: 'Regulatory approval processes vary by country. Data privacy compliance (HIPAA, GDPR, local laws). High customer acquisition costs.',
    exitOpportunities: 'Acquisition by major healthcare conglomerates. Series C funding round. Regional healthcare system integrations.',
    developmentCost: 780000, infrastructureCost: 250000, marketingCost: 350000, legalCost: 180000, operationalCost: 420000, technologyCost: 520000, maintenanceCost: 180000,
    totalInvestment: 2680000, expectedROI: 280, monthlyRevenue: 95000, annualRevenue: 1140000, netProfit: 320000, ebitda: 480000,
    companyValuation: 12000000, suggestedSellingPrice: 15000000, reservePrice: 11000000, minimumOffer: 8000000,
    websiteUrl: 'https://mediconnect.ai', technologyStack: 'Python, TensorFlow, React Native, FastAPI, MongoDB, GCP',
    hostingProvider: 'Google Cloud', cloudInfrastructure: 'GCP with GPU clusters', sourceCodeAvailable: true,
    monthlyVisitors: 320000, monthlyActiveUsers: 28000, registeredUsers: 95000, customers: 12000, conversionRate: 4.1, seoScore: 72,
    aiValuation: 13500000, investorPrice: 10000000, wholesalePrice: 9000000, acquisitionPrice: 15000000,
    tags: 'ai,healthcare,telemedicine,diagnostics,mena,healthtech',
    sellerId: 'user_3', images: '', thumbnail: '',
  },
  {
    id: 'proj_3', name: 'ShopEase Plus', category: 'ecommerce', industry: 'Retail', country: 'India', city: 'Bangalore',
    businessStage: 'growth', foundedYear: 2020, status: 'active', visibility: 'public', featured: true,
    overview: 'ShopEase Plus is a multi-vendor e-commerce platform specializing in South Asian fashion, home goods, and electronics. The platform processes over 15,000 orders daily with a network of 3,000+ verified sellers.',
    businessModel: 'Multi-vendor marketplace with commission-based revenue. Platform takes 8-15% commission on each transaction.',
    targetMarket: 'Indian consumers aged 18-45, with growing presence in Bangladesh, Pakistan, and Sri Lanka.',
    revenueModel: 'Seller commissions, premium seller subscriptions, advertising, and logistics services.',
    growthOpportunity: 'Cross-border e-commerce expansion. Private label products. Same-day delivery in top 20 cities.',
    competitiveAdvantage: 'Localized payment solutions (UPI, bKash, Easypaisa). Vernacular language support for 12+ languages. Strong seller onboarding program.',
    businessRisks: 'Intense competition from Amazon and Flipkart. Regulatory changes in e-commerce FDI policy. Logistics challenges in tier-2/3 cities.',
    exitOpportunities: 'Strategic acquisition by regional e-commerce player. Merger with complementary platform. PE/VC growth round.',
    developmentCost: 650000, infrastructureCost: 380000, marketingCost: 1200000, legalCost: 150000, operationalCost: 890000, technologyCost: 420000, maintenanceCost: 240000,
    totalInvestment: 3930000, expectedROI: 220, monthlyRevenue: 420000, annualRevenue: 5040000, netProfit: 760000, ebitda: 1100000,
    companyValuation: 28000000, suggestedSellingPrice: 32000000, reservePrice: 25000000, minimumOffer: 20000000, buyNowPrice: 35000000,
    websiteUrl: 'https://shopeaseplus.in', technologyStack: 'Next.js, Node.js, PostgreSQL, Redis, Elasticsearch, AWS, Docker',
    hostingProvider: 'AWS', cloudInfrastructure: 'Multi-region AWS with CloudFront CDN', sourceCodeAvailable: true,
    monthlyVisitors: 4500000, monthlyActiveUsers: 1200000, registeredUsers: 8500000, customers: 3200000, subscribers: 180000, conversionRate: 3.8, seoScore: 91,
    aiValuation: 29500000, investorPrice: 25000000, wholesalePrice: 22000000, acquisitionPrice: 32000000,
    tags: 'ecommerce,marketplace,fashion,retail,india,south-asia',
    sellerId: 'user_4', images: '', thumbnail: '',
  },
  {
    id: 'proj_4', name: 'FinanceFlow CRM', category: 'crm-erp', industry: 'FinTech', country: 'United Kingdom', city: 'London',
    businessStage: 'mature', foundedYear: 2018, status: 'active', visibility: 'public', featured: true,
    overview: 'FinanceFlow CRM is a specialized customer relationship management platform built for financial advisors, wealth managers, and investment firms. It integrates portfolio tracking, compliance management, and client communication tools.',
    businessModel: 'B2B SaaS with tiered pricing. Starter ($79/user/month), Professional ($149/user/month), Enterprise (custom pricing).',
    targetMarket: 'Financial advisory firms, wealth management companies, family offices, and independent financial advisors in Europe and North America.',
    revenueModel: 'SaaS subscriptions, implementation services, premium support, and data integration add-ons.',
    growthOpportunity: 'US market expansion. AI-driven financial insights feature. Open banking API integrations.',
    competitiveAdvantage: 'MiFID II compliant out of the box. Deep integrations with Bloomberg, Reuters, and major custodians. White-label option for enterprise.',
    businessRisks: 'Financial regulation complexity across jurisdictions. High customer concentration in UK market. Data security requirements.',
    exitOpportunities: 'Acquisition by larger FinTech or CRM company. Strategic partnership with major banks. Secondary buyout.',
    developmentCost: 920000, infrastructureCost: 280000, marketingCost: 450000, legalCost: 320000, operationalCost: 560000, technologyCost: 380000, maintenanceCost: 190000,
    totalInvestment: 3100000, expectedROI: 410, monthlyRevenue: 310000, annualRevenue: 3720000, netProfit: 1450000, ebitda: 1780000,
    companyValuation: 35000000, suggestedSellingPrice: 42000000, reservePrice: 35000000, minimumOffer: 30000000, buyNowPrice: 45000000,
    websiteUrl: 'https://financeflow.io', technologyStack: 'React, .NET Core, SQL Server, Redis, Azure, Azure DevOps',
    hostingProvider: 'Microsoft Azure', cloudInfrastructure: 'Azure with geo-redundant storage', sourceCodeAvailable: true,
    monthlyVisitors: 280000, monthlyActiveUsers: 8500, registeredUsers: 35000, customers: 4200, subscribers: 4200, conversionRate: 7.8, seoScore: 82,
    aiValuation: 38500000, investorPrice: 32000000, wholesalePrice: 29000000, acquisitionPrice: 42000000,
    tags: 'crm,fintech,finance,wealth-management,compliance,b2b',
    sellerId: 'user_2', images: '', thumbnail: '',
  },
  {
    id: 'proj_5', name: 'LearnPath Academy', category: 'edtech', industry: 'Education', country: 'Singapore', city: 'Singapore',
    businessStage: 'growth', foundedYear: 2022, status: 'active', visibility: 'public', featured: false,
    overview: 'LearnPath Academy is an AI-adaptive online learning platform for K-12 and university students across Asia-Pacific. Features include personalized learning paths, AI tutoring, peer collaboration, and progress analytics.',
    businessModel: 'Freemium model with premium subscriptions. Basic content free, premium features at $19/month (student) or $49/month (institutional).',
    targetMarket: 'Students aged 8-25, schools, tutoring centers, and universities in APAC region.',
    revenueModel: 'Premium subscriptions, institutional licenses, content creation partnerships, and certification programs.',
    growthOpportunity: 'Content localization for 10+ Asian languages. Government education contracts. AI assessment engine for standardized tests.',
    competitiveAdvantage: 'AI adapts to individual learning speed and style. Gamification with 95% engagement rate. Curriculum-aligned content for 8 countries.',
    businessRisks: 'Content licensing costs. Competition from established players. Education policy changes.',
    exitOpportunities: 'Acquisition by global edtech company. Partnership with major universities. Series B/C funding.',
    developmentCost: 540000, infrastructureCost: 180000, marketingCost: 380000, legalCost: 120000, operationalCost: 290000, technologyCost: 340000, maintenanceCost: 95000,
    totalInvestment: 1945000, expectedROI: 290, monthlyRevenue: 128000, annualRevenue: 1536000, netProfit: 420000, ebitda: 580000,
    companyValuation: 15000000, suggestedSellingPrice: 18000000, reservePrice: 14000000, minimumOffer: 11000000,
    websiteUrl: 'https://learnpath.academy', technologyStack: 'Vue.js, Python, Django, PostgreSQL, TensorFlow, AWS',
    hostingProvider: 'AWS', cloudInfrastructure: 'AWS with CloudFront and Lambda', sourceCodeAvailable: true,
    monthlyVisitors: 1200000, monthlyActiveUsers: 185000, registeredUsers: 920000, customers: 45000, subscribers: 28000, conversionRate: 5.1, seoScore: 78,
    aiValuation: 16200000, investorPrice: 13000000, wholesalePrice: 12000000, acquisitionPrice: 18000000,
    tags: 'edtech,education,ai,learning,k12,apac,online-learning',
    sellerId: 'user_3', images: '', thumbnail: '',
  },
  {
    id: 'proj_6', name: 'SecureVault Cyber', category: 'cybersecurity', industry: 'Technology', country: 'Israel', city: 'Tel Aviv',
    businessStage: 'growth', foundedYear: 2021, status: 'active', visibility: 'public', featured: false,
    overview: 'SecureVault Cyber provides enterprise cybersecurity solutions including threat detection, zero-trust network access, and automated incident response. Protects over 500 enterprise clients across 40 countries.',
    businessModel: 'B2B enterprise SaaS. Annual contracts with per-endpoint pricing. Professional services for implementation.',
    targetMarket: 'Mid to large enterprises (500+ employees) in finance, healthcare, government, and technology sectors.',
    revenueModel: 'Annual SaaS contracts ($50-200/endpoint/year), professional services, training, and 24/7 SOC services.',
    growthOpportunity: 'XDR platform expansion. Government contracts. MSP/VAR channel development.',
    competitiveAdvantage: 'AI-powered threat detection with 99.7% accuracy. 3-minute average incident response time. ISO 27001 and SOC 2 certified.',
    businessRisks: 'High talent acquisition costs. Evolving threat landscape. Regulatory compliance burden.',
    exitOpportunities: 'Acquisition by major cybersecurity vendor. Strategic investment from defense contractors. IPO preparation.',
    developmentCost: 1200000, infrastructureCost: 450000, marketingCost: 600000, legalCost: 280000, operationalCost: 890000, technologyCost: 720000, maintenanceCost: 310000,
    totalInvestment: 4450000, expectedROI: 380, monthlyRevenue: 520000, annualRevenue: 6240000, netProfit: 2100000, ebitda: 2900000,
    companyValuation: 55000000, suggestedSellingPrice: 65000000, reservePrice: 52000000, minimumOffer: 45000000,
    websiteUrl: 'https://securevault.io', technologyStack: 'Go, Rust, Python, Elasticsearch, Kafka, AWS, Kubernetes',
    hostingProvider: 'AWS', cloudInfrastructure: 'Multi-region AWS with dedicated VPCs', sourceCodeAvailable: false,
    monthlyVisitors: 180000, monthlyActiveUsers: 12000, registeredUsers: 45000, customers: 520, conversionRate: 8.5, seoScore: 74,
    aiValuation: 58000000, investorPrice: 48000000, wholesalePrice: 44000000, acquisitionPrice: 65000000,
    tags: 'cybersecurity,enterprise,threat-detection,zero-trust,ai,security',
    sellerId: 'user_1', images: '', thumbnail: '',
  },
  {
    id: 'proj_7', name: 'GreenVilla Estates', category: 'real-estate', industry: 'Real Estate', country: 'Canada', city: 'Toronto',
    businessStage: 'mature', foundedYear: 2017, status: 'active', visibility: 'public', featured: true,
    overview: 'GreenVilla Estates is a premium sustainable real estate development company specializing in eco-friendly residential and commercial properties in the Greater Toronto Area. Portfolio includes 12 completed developments with 850+ units.',
    businessModel: 'Property development and management. Revenue from unit sales, property management fees, and rental income.',
    targetMarket: 'High-net-worth individuals, environmentally conscious buyers, and corporate tenants in the Toronto metropolitan area.',
    revenueModel: 'Property sales, long-term rental income, property management fees (8% of rent), and green certification consulting.',
    growthOpportunity: 'Expansion to Vancouver and Montreal. Net-zero energy building technology. Affordable housing segment.',
    competitiveAdvantage: 'LEED Platinum certified developments. Proprietary modular construction reducing costs by 25%. Strong brand recognition in eco-luxury segment.',
    businessRisks: 'Interest rate sensitivity. Construction cost inflation. Regulatory approval timelines. Market cyclical nature.',
    exitOpportunities: 'Portfolio sale to REIT. Joint venture with institutional investor. Management buyout.',
    developmentCost: 8500000, infrastructureCost: 12000000, marketingCost: 1800000, legalCost: 950000, operationalCost: 2400000, technologyCost: 450000, maintenanceCost: 680000,
    totalInvestment: 26780000, expectedROI: 185, monthlyRevenue: 780000, annualRevenue: 9360000, netProfit: 2800000, ebitda: 4200000,
    companyValuation: 62000000, suggestedSellingPrice: 75000000, reservePrice: 60000000, minimumOffer: 55000000, buyNowPrice: 80000000,
    websiteUrl: 'https://greenvilla.ca', technologyStack: 'React, Node.js, PostgreSQL, Salesforce, AWS',
    hostingProvider: 'AWS', cloudInfrastructure: 'AWS with dedicated instances', sourceCodeAvailable: true,
    monthlyVisitors: 95000, monthlyActiveUsers: 8500, registeredUsers: 32000, customers: 1250, subscribers: 8000, conversionRate: 2.4, seoScore: 85,
    aiValuation: 67000000, investorPrice: 58000000, wholesalePrice: 52000000, acquisitionPrice: 75000000,
    tags: 'real-estate,sustainable,property,development,toronto,green,investment',
    sellerId: 'user_5', images: '', thumbnail: '',
  },
  {
    id: 'proj_8', name: 'FoodChain Pro', category: 'wholesale', industry: 'Food & Beverage', country: 'Brazil', city: 'São Paulo',
    businessStage: 'mature', foundedYear: 2016, status: 'active', visibility: 'public', featured: false,
    overview: 'FoodChain Pro is a B2B food wholesale and distribution platform connecting manufacturers with restaurants, hotels, and retailers across Brazil. Processes $15M+ in monthly transactions through its digital marketplace.',
    businessModel: 'B2B marketplace with logistics services. Commission on transactions (3-8%) plus delivery and warehousing fees.',
    targetMarket: 'Restaurants, hotels, supermarkets, and food retailers in Brazil\'s major metropolitan areas.',
    revenueModel: 'Transaction commissions, delivery fees, warehousing services, and premium supplier listings.',
    growthOpportunity: 'Cold chain logistics expansion. Cross-border trade with Mercosur countries. Private label products.',
    competitiveAdvantage: 'Largest food B2B network in Brazil. Real-time inventory management. Temperature-controlled logistics covering 18 states.',
    businessRisks: 'Supply chain disruptions. Currency fluctuation. Food safety regulations. Infrastructure challenges.',
    exitOpportunities: 'Acquisition by global food distribution company. Strategic partnership with major retailers. Regional expansion funding.',
    developmentCost: 380000, infrastructureCost: 2800000, marketingCost: 1200000, legalCost: 450000, operationalCost: 5200000, technologyCost: 680000, maintenanceCost: 340000,
    totalInvestment: 10750000, expectedROI: 165, monthlyRevenue: 680000, annualRevenue: 8160000, netProfit: 1950000, ebitda: 3200000,
    companyValuation: 48000000, suggestedSellingPrice: 55000000, reservePrice: 42000000, minimumOffer: 38000000,
    websiteUrl: 'https://foodchainpro.com.br', technologyStack: 'React, Python, Django, PostgreSQL, Redis, AWS, Docker',
    hostingProvider: 'AWS', cloudInfrastructure: 'AWS South America region', sourceCodeAvailable: true,
    monthlyVisitors: 650000, monthlyActiveUsers: 42000, registeredUsers: 185000, customers: 8500, conversionRate: 4.8, seoScore: 80,
    aiValuation: 51000000, investorPrice: 42000000, wholesalePrice: 38000000, acquisitionPrice: 55000000,
    tags: 'wholesale,food,distribution,b2b,brazil,logistics,marketplace',
    sellerId: 'user_6', images: '', thumbnail: '',
  },
  {
    id: 'proj_9', name: 'QuickBite Express', category: 'retail', industry: 'Food & Beverage', country: 'Pakistan', city: 'Karachi',
    businessStage: 'growth', foundedYear: 2022, status: 'active', visibility: 'public', featured: false,
    overview: 'QuickBite Express is a fast-growing cloud kitchen franchise with 25 locations across Pakistan. Specializes in local cuisine with modern delivery-first model. Average order value $8 with 22-minute delivery time.',
    businessModel: 'Cloud kitchen franchise with central commissary model. Franchise fees + revenue sharing with franchisees.',
    targetMarket: 'Urban professionals and families in Pakistani cities aged 18-45. Growing middle class with increasing digital adoption.',
    revenueModel: 'Direct sales (70%), franchise fees (15%), delivery commissions (15%). Average unit revenue $35,000/month.',
    growthOpportunity: 'Expansion to 100 locations by 2026. International franchise in GCC. Ghost kitchen technology licensing.',
    competitiveAdvantage: 'Proprietary recipe management system. 22-minute average delivery. 92% customer satisfaction rating.',
    businessRisks: 'Food cost inflation. Delivery logistics. Franchise quality control. Regulatory compliance.',
    exitOpportunities: 'Acquisition by food delivery platform. Private equity investment. Regional franchise deal.',
    developmentCost: 280000, infrastructureCost: 1800000, marketingCost: 650000, legalCost: 120000, operationalCost: 3200000, technologyCost: 180000, maintenanceCost: 95000,
    totalInvestment: 6325000, expectedROI: 195, monthlyRevenue: 420000, annualRevenue: 5040000, netProfit: 980000, ebitda: 1350000,
    companyValuation: 18000000, suggestedSellingPrice: 22000000, reservePrice: 16000000, minimumOffer: 14000000,
    websiteUrl: 'https://quickbite.pk', technologyStack: 'React Native, Node.js, MongoDB, Redis, AWS',
    hostingProvider: 'AWS', cloudInfrastructure: 'AWS Asia Pacific', sourceCodeAvailable: true,
    monthlyVisitors: 380000, monthlyActiveUsers: 95000, registeredUsers: 420000, customers: 180000, subscribers: 65000, conversionRate: 6.8, seoScore: 76,
    aiValuation: 19500000, investorPrice: 15000000, wholesalePrice: 13500000, acquisitionPrice: 22000000,
    tags: 'retail,food,cloud-kitchen,franchise,pakistan,delivery,restaurant',
    sellerId: 'user_4', images: '', thumbnail: '',
  },
  {
    id: 'proj_10', name: 'AutoInvest Platform', category: 'investments', industry: 'FinTech', country: 'United States', city: 'New York',
    businessStage: 'startup', foundedYear: 2023, status: 'active', visibility: 'public', featured: false,
    overview: 'AutoInvest Platform is a robo-advisory and automated investment platform targeting millennials and Gen Z investors. Features include AI portfolio management, fractional investing, social trading, and ESG-focused investment options.',
    businessModel: 'B2C fintech with freemium model. Basic portfolio management free. Premium features at $9.99/month. Managed portfolios with 0.25% AUM fee.',
    targetMarket: 'Young investors aged 18-35 in the US, seeking accessible investment tools with social features.',
    revenueModel: 'Premium subscriptions, AUM management fees, payment for order flow, and partnership referrals.',
    growthOpportunity: 'Cryptocurrency integration. Auto-investing round-ups with banks. International expansion to EU and UK.',
    competitiveAdvantage: 'Social investing features with verified trader leaderboards. ESG scoring on all investments. Gamified learning modules.',
    businessRisks: 'SEC/FINRA regulatory requirements. Market downturn impact on user engagement. Competition from established brokerages.',
    exitOpportunities: 'Acquisition by traditional brokerage. Series B funding. Banking license application.',
    developmentCost: 520000, infrastructureCost: 180000, marketingCost: 450000, legalCost: 280000, operationalCost: 320000, technologyCost: 280000, maintenanceCost: 95000,
    totalInvestment: 2125000, expectedROI: 420, monthlyRevenue: 65000, annualRevenue: 780000, netProfit: 85000, ebitda: 180000,
    companyValuation: 8500000, suggestedSellingPrice: 12000000, reservePrice: 8000000, minimumOffer: 6000000,
    websiteUrl: 'https://autoinvest.app', technologyStack: 'React Native, Python, FastAPI, PostgreSQL, Redis, AWS',
    hostingProvider: 'AWS', cloudInfrastructure: 'AWS with multi-AZ deployment', sourceCodeAvailable: true,
    monthlyVisitors: 420000, monthlyActiveUsers: 65000, registeredUsers: 280000, customers: 85000, subscribers: 12000, conversionRate: 5.2, seoScore: 68,
    aiValuation: 9200000, investorPrice: 7000000, wholesalePrice: 6200000, acquisitionPrice: 12000000,
    tags: 'investments,fintech,robo-advisor,esg,social-trading,millennials',
    sellerId: 'user_2', images: '', thumbnail: '',
  },
  {
    id: 'proj_11', name: 'DataPipe Analytics', category: 'saas', industry: 'Technology', country: 'Germany', city: 'Berlin',
    businessStage: 'growth', foundedYear: 2020, status: 'active', visibility: 'public', featured: false,
    overview: 'DataPipe Analytics is a no-code data pipeline and analytics platform that enables businesses to connect, transform, and visualize data from 150+ sources without writing code. Used by 2,800+ companies across Europe.',
    businessModel: 'SaaS with usage-based pricing. Free tier (100K rows/month), Growth ($99/month), Pro ($299/month), Enterprise (custom).',
    targetMarket: 'Data teams, business analysts, and operations teams at mid-market companies in Europe and North America.',
    revenueModel: 'SaaS subscriptions, enterprise contracts, professional services, and marketplace connectors.',
    growthOpportunity: 'AI-powered data quality features. Real-time streaming capabilities. Data governance module.',
    competitiveAdvantage: '150+ pre-built connectors. Sub-5-minute setup time. GDPR compliance built-in. Best-in-class European data residency.',
    businessRisks: 'GDPR compliance costs. Competition from established ETL tools. Data connector maintenance burden.',
    exitOpportunities: 'Acquisition by larger data platform. Series C funding. Strategic OEM partnerships.',
    developmentCost: 680000, infrastructureCost: 220000, marketingCost: 380000, legalCost: 195000, operationalCost: 450000, technologyCost: 320000, maintenanceCost: 140000,
    totalInvestment: 2385000, expectedROI: 310, monthlyRevenue: 210000, annualRevenue: 2520000, netProfit: 680000, ebitda: 920000,
    companyValuation: 22000000, suggestedSellingPrice: 26000000, reservePrice: 20000000, minimumOffer: 17000000,
    websiteUrl: 'https://datapipe.dev', technologyStack: 'React, Go, Apache Kafka, PostgreSQL, ClickHouse, GCP',
    hostingProvider: 'Google Cloud', cloudInfrastructure: 'GCP with multi-region deployment', sourceCodeAvailable: true,
    monthlyVisitors: 520000, monthlyActiveUsers: 38000, registeredUsers: 145000, customers: 2800, subscribers: 2800, conversionRate: 5.8, seoScore: 83,
    aiValuation: 23500000, investorPrice: 19000000, wholesalePrice: 17000000, acquisitionPrice: 26000000,
    tags: 'saas,analytics,data-pipeline,no-code,etl,business-intelligence',
    sellerId: 'user_1', images: '', thumbnail: '',
  },
  {
    id: 'proj_12', name: 'EstateVault Digital', category: 'domains', industry: 'Technology', country: 'Australia', city: 'Sydney',
    businessStage: 'mature', foundedYear: 2015, status: 'active', visibility: 'public', featured: false,
    overview: 'EstateVault Digital manages a premium portfolio of 2,400+ domain names and 15 developed web properties generating passive income through advertising, affiliate marketing, and premium domain sales.',
    businessModel: 'Domain portfolio management and monetization. Revenue from parking, development, and premium sales.',
    targetMarket: 'Businesses seeking premium domains, advertising networks, and strategic acquirers.',
    revenueModel: 'Domain parking revenue, premium domain sales ($5K-$500K), developed site revenue, and leasing.',
    growthOpportunity: 'AI-powered domain valuation tool. Blockchain domain integration. Web3 marketplace development.',
    competitiveAdvantage: '2,400+ premium domains including 85 single-word .com domains. Average 12-year portfolio age. SEO authority on developed sites.',
    businessRisks: 'Domain renewal costs. Market saturation for new gTLDs. Changes in search engine algorithms.',
    exitOpportunities: 'Portfolio acquisition by domain investor. Individual premium sales. Partnership with registry.',
    developmentCost: 120000, infrastructureCost: 45000, marketingCost: 85000, legalCost: 35000, operationalCost: 65000, technologyCost: 28000, maintenanceCost: 42000,
    totalInvestment: 420000, expectedROI: 520, monthlyRevenue: 95000, annualRevenue: 1140000, netProfit: 820000, ebitda: 950000,
    companyValuation: 14500000, suggestedSellingPrice: 18000000, reservePrice: 14000000, minimumOffer: 12000000, buyNowPrice: 20000000,
    websiteUrl: 'https://estatevault.com', technologyStack: 'WordPress, PHP, Cloudflare, Google AdSense',
    hostingProvider: 'Cloudflare + DigitalOcean', cloudInfrastructure: 'Cloudflare CDN with edge computing', sourceCodeAvailable: true,
    monthlyVisitors: 2800000, monthlyActiveUsers: 450000, registeredUsers: 0, customers: 0, conversionRate: 0, seoScore: 92,
    aiValuation: 15800000, investorPrice: 13000000, wholesalePrice: 12000000, acquisitionPrice: 18000000,
    tags: 'domains,digital-assets,passive-income,portfolio,premium-domains',
    sellerId: 'user_5', images: '', thumbnail: '',
  },
];

export async function seedDatabase() {
  // Seed categories
  for (const cat of CATEGORIES) {
    await db.category.upsert({
      where: { slug: cat.slug },
      update: { name: cat.name, icon: cat.icon, description: cat.description, order: cat.order },
      create: { id: cat.id, name: cat.name, slug: cat.slug, icon: cat.icon, description: cat.description, order: cat.order },
    });
  }

  // Seed users
  for (const user of SEED_USERS) {
    await db.user.upsert({
      where: { email: user.email },
      update: { name: user.name, role: user.role, company: user.company, country: user.country, city: user.city, verified: user.verified },
      create: user,
    });
  }

  // Seed projects
  for (const proj of SEED_PROJECTS) {
    const existing = await db.project.findUnique({ where: { id: proj.id } });
    if (!existing) {
      await db.project.create({ data: proj as any });
    }
  }

  return { categories: CATEGORIES.length, users: SEED_USERS.length, projects: SEED_PROJECTS.length };
}