import type { Project } from './types';

/* ─── Static Seller ─── */
const SELLER = {
  id: 'seller_pbd_001',
  name: 'PlayBeat Digital',
  company: 'PlayBeat Digital',
  country: 'Pakistan',
  avatar: undefined as string | undefined,
  verified: true,
  bio: 'Premium digital asset portfolio — domains, SaaS platforms, and crypto exchange properties.',
};

/* ─── Static Categories (with project counts) ─── */
export const STATIC_CATEGORIES = [
  { id: 'cat_domains', name: 'Domains', slug: 'domains', icon: 'globe', description: 'Premium domain names for branding and business', parent: null, order: 1, _count: { projects: 4 } },
  { id: 'cat_fintech', name: 'FinTech', slug: 'fintech', icon: 'wallet', description: 'Crypto exchanges, trading platforms, and financial technology', parent: null, order: 2, _count: { projects: 4 } },
  { id: 'cat_digital', name: 'Digital Products', slug: 'digital-products', icon: 'package', description: 'Media platforms, content tools, and digital assets', parent: null, order: 3, _count: { projects: 1 } },
  { id: 'cat_websites', name: 'Websites', slug: 'websites', icon: 'layout', description: 'Fully built web applications and SaaS platforms', parent: null, order: 4, _count: { projects: 2 } },
];

/* ─── 11 Products with exact USD prices ─── */
export const STATIC_PRODUCTS: Project[] = [
  {
    id: 'proj_playbeat_live',
    name: 'PlayBeat.live',
    category: 'domains',
    industry: 'Media & Entertainment',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: true,
    overview: 'Premium .live domain ideal for live-streaming, music platforms, or entertainment brands. Short, memorable, and highly brandable.',
    businessModel: 'Domain Sale',
    targetMarket: 'Entertainment companies, streaming platforms',
    technologyStack: 'DNS, Web Hosting',
    tags: 'domain,live,streaming,music',
    websiteUrl: 'https://playbeat.live',
    suggestedSellingPrice: 1800,
    buyNowPrice: 1800,
    investorPrice: 1530,
    wholesalePrice: 1350,
    acquisitionPrice: 2160,
    minimumOffer: 1260,
    sourceCodeAvailable: false,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 0, favorites: 3 },
    createdAt: '2025-01-15T10:00:00.000Z',
    updatedAt: '2025-01-15T10:00:00.000Z',
  },
  {
    id: 'proj_playbeat_digital',
    name: 'PlayBeat.digital',
    category: 'domains',
    industry: 'Digital Services',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: true,
    overview: 'Premium .digital domain perfect for a digital agency, tech startup, or creative studio. Modern and authoritative TLD.',
    businessModel: 'Brand Sale',
    targetMarket: 'Digital agencies, tech startups',
    technologyStack: 'Next.js, React',
    tags: 'domain,digital,agency',
    websiteUrl: 'https://playbeat.digital',
    suggestedSellingPrice: 2000,
    buyNowPrice: 2000,
    investorPrice: 1700,
    wholesalePrice: 1500,
    acquisitionPrice: 2400,
    minimumOffer: 1400,
    sourceCodeAvailable: false,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 1, favorites: 5 },
    createdAt: '2025-01-15T10:01:00.000Z',
    updatedAt: '2025-01-15T10:01:00.000Z',
  },
  {
    id: 'proj_playbeatdigital_world',
    name: 'PlayBeatDigital.world',
    category: 'domains',
    industry: 'Media & Entertainment',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: true,
    overview: 'Global-ready .world domain for the PlayBeat Digital brand. Excellent for international expansion and global media presence.',
    businessModel: 'Domain Sale',
    targetMarket: 'Global media companies, international brands',
    technologyStack: 'DNS, Web Hosting',
    tags: 'domain,world,global',
    websiteUrl: 'https://playbeatdigital.world',
    suggestedSellingPrice: 2000,
    buyNowPrice: 2000,
    investorPrice: 1700,
    wholesalePrice: 1500,
    acquisitionPrice: 2400,
    minimumOffer: 1400,
    sourceCodeAvailable: false,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 0, favorites: 2 },
    createdAt: '2025-01-15T10:02:00.000Z',
    updatedAt: '2025-01-15T10:02:00.000Z',
  },
  {
    id: 'proj_blockexchange',
    name: 'BlockExchange.buzz',
    category: 'fintech',
    industry: 'Cryptocurrency & Blockchain',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: true,
    overview: 'Fully functional cryptocurrency exchange platform with real-time trading, order books, and WebSocket-based price feeds. Built with React and Node.js.',
    businessModel: 'Trading Fees',
    targetMarket: 'Crypto traders, DeFi enthusiasts',
    technologyStack: 'React, Node.js, WebSocket',
    tags: 'crypto,exchange,blockchain,defi',
    websiteUrl: 'https://blockexchange.buzz',
    monthlyVisitors: 500,
    suggestedSellingPrice: 1900,
    buyNowPrice: 1900,
    investorPrice: 1615,
    wholesalePrice: 1425,
    acquisitionPrice: 2280,
    minimumOffer: 1330,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 2, favorites: 8 },
    createdAt: '2025-01-15T10:03:00.000Z',
    updatedAt: '2025-01-15T10:03:00.000Z',
  },
  {
    id: 'proj_brockexchange',
    name: 'BrockExchange.quest',
    category: 'fintech',
    industry: 'Cryptocurrency & Blockchain',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: false,
    overview: 'Cryptocurrency trading platform with a modern UI. Features include market dashboards, portfolio tracking, and trade execution.',
    businessModel: 'Trading Fees',
    targetMarket: 'Retail traders, crypto beginners',
    technologyStack: 'React, Node.js',
    tags: 'crypto,exchange,trading',
    websiteUrl: 'https://brockexchange.quest',
    monthlyVisitors: 300,
    suggestedSellingPrice: 1900,
    buyNowPrice: 1900,
    investorPrice: 1615,
    wholesalePrice: 1425,
    acquisitionPrice: 2280,
    minimumOffer: 1330,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 0, favorites: 1 },
    createdAt: '2025-01-15T10:04:00.000Z',
    updatedAt: '2025-01-15T10:04:00.000Z',
  },
  {
    id: 'proj_buzzcryp',
    name: 'BuzzCryp.buzz',
    category: 'fintech',
    industry: 'Cryptocurrency & Blockchain',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: false,
    overview: 'Crypto news and community platform with content aggregation, price trackers, and community forums for blockchain enthusiasts.',
    businessModel: 'Ads, Subscriptions',
    targetMarket: 'Crypto community, blockchain developers',
    technologyStack: 'Next.js, Tailwind CSS',
    tags: 'crypto,news,community',
    websiteUrl: 'https://buzzcryp.buzz',
    monthlyVisitors: 400,
    suggestedSellingPrice: 1900,
    buyNowPrice: 1900,
    investorPrice: 1615,
    wholesalePrice: 1425,
    acquisitionPrice: 2280,
    minimumOffer: 1330,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 0, favorites: 2 },
    createdAt: '2025-01-15T10:05:00.000Z',
    updatedAt: '2025-01-15T10:05:00.000Z',
  },
  {
    id: 'proj_nextradepro',
    name: 'NexTradePro.top',
    category: 'fintech',
    industry: 'Technology',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: false,
    overview: 'Professional trading platform with advanced charting, technical analysis tools, and SaaS subscription model. Built for serious traders and fintech startups.',
    businessModel: 'SaaS Subscription',
    targetMarket: 'Traders, fintech startups',
    technologyStack: 'Next.js, TypeScript',
    tags: 'trading,fintech,crypto,saas',
    websiteUrl: 'https://nextradepro.top',
    suggestedSellingPrice: 900,
    buyNowPrice: 900,
    investorPrice: 765,
    wholesalePrice: 675,
    acquisitionPrice: 1080,
    minimumOffer: 630,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 1, favorites: 4 },
    createdAt: '2025-01-15T10:06:00.000Z',
    updatedAt: '2025-01-15T10:06:00.000Z',
  },
  {
    id: 'proj_playbeattv',
    name: 'PlayBeatTV.buzz',
    category: 'domains',
    industry: 'Media & Entertainment',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: true,
    overview: 'Premium .buzz domain for a TV/streaming brand. Perfect for video content platforms, live streaming services, or entertainment networks.',
    businessModel: 'Streaming Platform',
    targetMarket: 'Media companies, content creators',
    technologyStack: 'React, Node.js, CDN',
    tags: 'streaming,tv,video,domain',
    websiteUrl: 'https://playbeattv.buzz',
    suggestedSellingPrice: 1400,
    buyNowPrice: 1400,
    investorPrice: 1190,
    wholesalePrice: 1050,
    acquisitionPrice: 1680,
    minimumOffer: 980,
    sourceCodeAvailable: false,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 0, favorites: 3 },
    createdAt: '2025-01-15T10:07:00.000Z',
    updatedAt: '2025-01-15T10:07:00.000Z',
  },
  {
    id: 'proj_magxtv',
    name: 'MagxTV',
    category: 'digital-products',
    industry: 'Media & Entertainment',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: false,
    overview: 'Media and content platform at magxtv.click. Designed for content creators with CMS integration, video hosting, and audience engagement features.',
    businessModel: 'Content Platform',
    targetMarket: 'Content creators, media companies',
    technologyStack: 'Next.js, CMS',
    tags: 'media,tv,content,video',
    websiteUrl: 'https://magxtv.click',
    suggestedSellingPrice: 1900,
    buyNowPrice: 1900,
    investorPrice: 1615,
    wholesalePrice: 1425,
    acquisitionPrice: 2280,
    minimumOffer: 1330,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 0, favorites: 1 },
    createdAt: '2025-01-15T10:08:00.000Z',
    updatedAt: '2025-01-15T10:08:00.000Z',
  },
  {
    id: 'proj_malik_indol',
    name: 'Malik Indol',
    category: 'websites',
    industry: 'Technology',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: true,
    overview: 'Full-stack SaaS web application deployed on Vercel. Enterprise-ready with modern architecture, responsive design, and production-grade TypeScript codebase.',
    businessModel: 'SaaS Platform',
    targetMarket: 'Enterprise, B2B',
    technologyStack: 'Next.js, React, TypeScript, Vercel',
    tags: 'saas,webapp,vercel,enterprise',
    websiteUrl: 'https://malik-indol-six.vercel.app',
    demoUrl: 'https://malik-indol-six.vercel.app',
    monthlyVisitors: 1000,
    suggestedSellingPrice: 1800,
    buyNowPrice: 1800,
    investorPrice: 1530,
    wholesalePrice: 1350,
    acquisitionPrice: 2160,
    minimumOffer: 1260,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 2, favorites: 6 },
    createdAt: '2025-01-15T10:09:00.000Z',
    updatedAt: '2025-01-15T10:09:00.000Z',
  },
  {
    id: 'proj_zxc_sigma',
    name: 'ZXC Sigma Ivory',
    category: 'websites',
    industry: 'Technology',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: true,
    overview: 'Production SaaS application deployed on Vercel. Features modern UI, clean codebase, and is ready for immediate commercial use or further development.',
    businessModel: 'SaaS / Productivity',
    targetMarket: 'Business professionals, startups',
    technologyStack: 'Next.js, React, TypeScript, Vercel',
    tags: 'saas,webapp,vercel,productivity',
    websiteUrl: 'https://zxc-sigma-ivory.vercel.app',
    demoUrl: 'https://zxc-sigma-ivory.vercel.app',
    monthlyVisitors: 750,
    suggestedSellingPrice: 1200,
    buyNowPrice: 1200,
    investorPrice: 1020,
    wholesalePrice: 900,
    acquisitionPrice: 1440,
    minimumOffer: 840,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 1, favorites: 4 },
    createdAt: '2025-01-15T10:10:00.000Z',
    updatedAt: '2025-01-15T10:10:00.000Z',
  },
];

/** Find a project by its static ID */
export function findStaticProject(id: string): Project | undefined {
  return STATIC_PRODUCTS.find((p) => p.id === id);
}
