import type { Project } from './types';

/* ─── Static Seller ─── */
const SELLER = {
  id: 'seller_pbd_001',
  name: 'PlayBeat Digital',
  company: 'PlayBeat Digital',
  country: 'Pakistan',
  avatar: undefined as string | undefined,
  verified: true,
  bio: 'Premium digital asset portfolio — SaaS platforms, digital marketplaces, crypto exchanges, IPTV platforms, and web applications.',
};

/* ─── Static Categories (with project counts) ─── */
export const STATIC_CATEGORIES = [
  { id: 'cat_domains', name: 'Domains', slug: 'domains', icon: 'globe', description: 'Premium domain names with deployed web applications', parent: null, order: 1, _count: { projects: 3 } },
  { id: 'cat_fintech', name: 'FinTech', slug: 'fintech', icon: 'wallet', description: 'Crypto exchanges, trading platforms, and financial technology', parent: null, order: 2, _count: { projects: 4 } },
  { id: 'cat_digital', name: 'Digital Products', slug: 'digital-products', icon: 'package', description: 'IPTV platforms, reseller panels, and digital asset management', parent: null, order: 3, _count: { projects: 2 } },
  { id: 'cat_websites', name: 'Websites', slug: 'websites', icon: 'layout', description: 'Fully built web applications, SaaS platforms, and marketplaces', parent: null, order: 4, _count: { projects: 3 } },
];

/* ─── 12 Products with real website data ─── */
export const STATIC_PRODUCTS: Project[] = [
  {
    id: 'proj_playbeat_live',
    name: 'PlayBeat.live',
    category: 'domains',
    industry: 'Media & Entertainment',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: true,
    overview: 'Live IPTV streaming platform with 11,000+ channels across 127+ categories. Features HLS.js streaming with auto-recovery, low-latency mode, smooth buffering, and instant channel switching. Includes admin panel for catalog management, email-based sign-in, and favorites sync across devices. Built with Next.js, MongoDB, and dark-themed UI.',
    businessModel: 'IPTV Streaming / SaaS',
    targetMarket: 'IPTV providers, streaming services, media companies',
    technologyStack: 'Next.js, Turbopack, MongoDB, HLS.js, Tailwind CSS',
    tags: 'iptv,streaming,live-channels,hls,media,mongodb',
    websiteUrl: 'https://playbeat.live',
    suggestedSellingPrice: 1800,
    buyNowPrice: 1800,
    investorPrice: 1530,
    wholesalePrice: 1350,
    acquisitionPrice: 2160,
    minimumOffer: 1260,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 0, favorites: 3 },
    createdAt: '2025-01-15T10:00:00.000Z',
    updatedAt: '2025-01-15T10:00:00.000Z',
  },
  {
    id: 'proj_playbeat_digital',
    name: 'PlayBeat.digital',
    category: 'domains',
    industry: 'E-Commerce',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: true,
    overview: 'Pakistan\'s premier digital marketplace with 500+ subscriptions across 50+ platforms. Sells game keys, software licenses, AI tools, streaming subscriptions (Netflix, Spotify, HBO Max, YouTube Premium), and gift cards with instant delivery under 60 seconds. Features dark/light theme, currency switcher, cart system, 12,000+ customers worldwide. Payments via JazzCash, PayPal, and Lemon Squeezy.',
    businessModel: 'Digital Marketplace',
    targetMarket: 'Digital resellers, gamers, software distributors',
    technologyStack: 'Next.js, Turbopack, Tailwind CSS, Lemon Squeezy',
    tags: 'marketplace,digital-products,game-keys,subscriptions,gift-cards',
    websiteUrl: 'https://playbeat.digital',
    monthlyVisitors: 5000,
    suggestedSellingPrice: 2000,
    buyNowPrice: 2000,
    investorPrice: 1700,
    wholesalePrice: 1500,
    acquisitionPrice: 2400,
    minimumOffer: 1400,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 1, favorites: 5 },
    createdAt: '2025-01-15T10:01:00.000Z',
    updatedAt: '2025-01-15T10:01:00.000Z',
  },
  {
    id: 'proj_playbeatdigital_world',
    name: 'PlayBeatDigital.world',
    category: 'domains',
    industry: 'E-Commerce / Gaming',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: true,
    overview: 'Global digital gaming marketplace with 52+ live products across 7 game categories (PUBG Mobile, Call of Duty, Free Fire, Steam, etc.). Features trending products section, affiliate hub, analytics dashboard, and mobile app. Supports 7 payment methods including Visa, Mastercard, JazzCash, Bank Alfalah, EasyPaisa, Payrails, and USDT crypto. Contact: WhatsApp 0332 102 9333.',
    businessModel: 'Digital Marketplace / Affiliate',
    targetMarket: 'Gaming community, digital product resellers worldwide',
    technologyStack: 'Next.js, Turbopack, Tailwind CSS, Sonner',
    tags: 'gaming,marketplace,game-keys,crypto-payments,affiliate',
    websiteUrl: 'https://playbeatdigital.world',
    monthlyVisitors: 3000,
    suggestedSellingPrice: 2000,
    buyNowPrice: 2000,
    investorPrice: 1700,
    wholesalePrice: 1500,
    acquisitionPrice: 2400,
    minimumOffer: 1400,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 0, favorites: 2 },
    createdAt: '2025-01-15T10:02:00.000Z',
    updatedAt: '2025-01-15T10:02:00.000Z',
  },
  {
    id: 'proj_blockexchange',
    name: 'BlockExchange.buzz',
    category: 'fintech',
    industry: 'Cryptocurrency & Blockchain',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: true,
    overview: 'Next-generation crypto trading platform for binary options on 10 cryptocurrencies. Features 30s/60s/120s contracts with up to 50% returns, real-time price tickers, VIP tier system (VIP-1 to Prime_Diamond), refer-and-earn $30 program, KYC verification, multi-currency wallet, and 24/7 support. Built with Next.js, Turbopack, Tailwind CSS v4, Geist fonts, and Sonner toasts. Includes admin panel and storefront. Contact: support@blockexchange.buzz.',
    businessModel: 'Binary Options Trading',
    targetMarket: 'Crypto traders, fintech entrepreneurs, white-label exchange operators',
    technologyStack: 'Next.js, Turbopack, Tailwind CSS v4, Geist Fonts, Sonner',
    tags: 'crypto,binary-options,trading,exchange,white-label',
    websiteUrl: 'https://blockexchange.buzz',
    monthlyVisitors: 500,
    suggestedSellingPrice: 1900,
    buyNowPrice: 1900,
    investorPrice: 1615,
    wholesalePrice: 1425,
    acquisitionPrice: 2280,
    minimumOffer: 1330,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 2, favorites: 8 },
    createdAt: '2025-01-15T10:03:00.000Z',
    updatedAt: '2025-01-15T10:03:00.000Z',
  },
  {
    id: 'proj_brockexchange',
    name: 'BrockExchange.quest',
    category: 'fintech',
    industry: 'Cryptocurrency & Blockchain',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: false,
    overview: 'White-label crypto binary options trading platform — mirror deployment of BlockExchange. Features 30s/60s/120s binary contracts on 10 cryptocurrencies with up to 50% returns, live price tickers, VIP rewards (VIP-1 to Prime_Diamond), $30 referral program, KYC verification, multi-currency wallet, and admin panel with storefront. Built with Next.js, Turbopack, Tailwind CSS v4, and Geist fonts. Contact: support@blockexchange.buzz.',
    businessModel: 'Binary Options Trading',
    targetMarket: 'Crypto entrepreneurs, exchange operators, white-label buyers',
    technologyStack: 'Next.js, Turbopack, Tailwind CSS v4, Geist Fonts, Sonner',
    tags: 'crypto,binary-options,trading,white-label,exchange',
    websiteUrl: 'https://brockexchange.quest',
    monthlyVisitors: 300,
    suggestedSellingPrice: 1900,
    buyNowPrice: 1900,
    investorPrice: 1615,
    wholesalePrice: 1425,
    acquisitionPrice: 2280,
    minimumOffer: 1330,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 0, favorites: 1 },
    createdAt: '2025-01-15T10:04:00.000Z',
    updatedAt: '2025-01-15T10:04:00.000Z',
  },
  {
    id: 'proj_buzzcryp',
    name: 'BuzzCryp.buzz',
    category: 'fintech',
    industry: 'Cryptocurrency & Blockchain',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: false,
    overview: 'Secure multi-tenant crypto trading platform with institutional-grade architecture. Features role-based access control (RBAC), database-level tenant isolation per Sub-Agent, 120+ crypto pairs, integrated wallet with admin approval pipeline, instant settlement, and full audit trails with IP/device tracking. Security: JWT + bcrypt (12 rounds), HTTP-only cookies, forced password change, password history. Supports BTC, ETH, BTG, BTS, USDT, SOL, ADA, XRP. Invitation-only access model.',
    businessModel: 'Institutional Trading Platform',
    targetMarket: 'Crypto brokerages, institutional traders, fintech companies',
    technologyStack: 'Next.js, Turbopack, Tailwind CSS, shadcn/ui, Geist Fonts, JWT, bcrypt',
    tags: 'crypto,trading,multi-tenant,rbac,institutional,security',
    websiteUrl: 'https://buzzcryp.buzz',
    monthlyVisitors: 400,
    suggestedSellingPrice: 1900,
    buyNowPrice: 1900,
    investorPrice: 1615,
    wholesalePrice: 1425,
    acquisitionPrice: 2280,
    minimumOffer: 1330,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 0, favorites: 2 },
    createdAt: '2025-01-15T10:05:00.000Z',
    updatedAt: '2025-01-15T10:05:00.000Z',
  },
  {
    id: 'proj_nextradepro',
    name: 'NexTradePro.top',
    category: 'fintech',
    industry: 'Cryptocurrency & Blockchain',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: false,
    overview: 'Professional binary options trading platform on 12+ crypto assets with tiered payouts: 20% (30s), 30% (60s), 50% (120s). Features pro charting with Bollinger Bands, MA, support/resistance, cold-storage wallet with multi-signature protection, invitation-code registration, membership/VIP program, $10,000 demo balance, and live market cards with sparklines. Built with Next.js, Turbopack, and Sonner toasts. Fully self-contained with zero external dependencies.',
    businessModel: 'Binary Options / SaaS',
    targetMarket: 'Fintech startups, trading platform operators',
    technologyStack: 'Next.js, Turbopack, Sonner',
    tags: 'crypto,binary-options,trading,charting,saas',
    websiteUrl: 'https://nextradepro.top',
    monthlyVisitors: 200,
    suggestedSellingPrice: 900,
    buyNowPrice: 900,
    investorPrice: 765,
    wholesalePrice: 675,
    acquisitionPrice: 1080,
    minimumOffer: 630,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 1, favorites: 4 },
    createdAt: '2025-01-15T10:06:00.000Z',
    updatedAt: '2025-01-15T10:06:00.000Z',
  },
  {
    id: 'proj_playbeattv',
    name: 'PlayBeatTV.buzz',
    category: 'digital-products',
    industry: 'Cybersecurity / Forensics',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: true,
    overview: 'Advanced Mobile Forensics (AMF) — forensic-grade mobile data recovery tool. Recovers deleted photos, messages, contacts, WhatsApp data, call logs, and documents. Features deep scan engine, SQLite forensics (live records + free-space carving), SHA-256 hash chain for court-admissible evidence, USB device connection with read-only safe scanning, and multi-format export (CSV, PDF, JSON, vCard). 100% local browser processing — data never leaves the machine. Supports 13+ data types across 6 scan modes.',
    businessModel: 'SaaS / Forensics Tool',
    targetMarket: 'Law enforcement, private investigators, cybersecurity firms',
    technologyStack: 'Next.js, Turbopack, Tailwind CSS v4, shadcn/ui, Geist Fonts, WebUSB',
    tags: 'forensics,data-recovery,security,mobile,tool,sha256',
    websiteUrl: 'https://playbeattv.buzz',
    monthlyVisitors: 800,
    suggestedSellingPrice: 1400,
    buyNowPrice: 1400,
    investorPrice: 1190,
    wholesalePrice: 1050,
    acquisitionPrice: 1680,
    minimumOffer: 980,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 0, favorites: 3 },
    createdAt: '2025-01-15T10:07:00.000Z',
    updatedAt: '2025-01-15T10:07:00.000Z',
  },
  {
    id: 'proj_magxtv',
    name: 'MagxTV',
    category: 'digital-products',
    industry: 'IPTV / Media',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: false,
    overview: 'MaGx World Super IPTV — enterprise-grade reseller panel (v2.4.1) with 30,000+ channels. Features fund management, IPTV line creation/management, automated payment processing, and multi-account authentication. Supports 4 social OAuth providers (Google, Facebook, X, TikTok), PayPal registration, and payment methods including JazzCash, Easypaisa, USDT crypto, and Bank Alfalah. Backend REST APIs for funds, payments, and line administration. Monetized with Google AdSense. Built with Next.js, Turbopack, shadcn/ui, and Lucide icons.',
    businessModel: 'IPTV Reseller Platform / SaaS',
    targetMarket: 'IPTV resellers, media distributors, telecom businesses',
    technologyStack: 'Next.js, Turbopack, Tailwind CSS, shadcn/ui, Lucide React, reCAPTCHA, AdSense',
    tags: 'iptv,reseller-panel,enterprise,subscriptions,payments',
    websiteUrl: 'https://magxtv.click',
    monthlyVisitors: 1500,
    suggestedSellingPrice: 1900,
    buyNowPrice: 1900,
    investorPrice: 1615,
    wholesalePrice: 1425,
    acquisitionPrice: 2280,
    minimumOffer: 1330,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 0, favorites: 1 },
    createdAt: '2025-01-15T10:08:00.000Z',
    updatedAt: '2025-01-15T10:08:00.000Z',
  },
  {
    id: 'proj_malik_indol',
    name: 'Malik Indol',
    category: 'websites',
    industry: 'Technology',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: true,
    overview: 'Full-stack SaaS web application deployed on Vercel. Enterprise-ready with modern architecture, responsive design, and production-grade TypeScript codebase. Includes user authentication, dashboard, and admin panel.',
    businessModel: 'SaaS Platform',
    targetMarket: 'Enterprise, B2B',
    technologyStack: 'Next.js, React, TypeScript, Vercel',
    tags: 'saas,webapp,vercel,enterprise',
    websiteUrl: 'https://malik-indol-six.vercel.app',
    demoUrl: 'https://malik-indol-six.vercel.app',
    monthlyVisitors: 1000,
    suggestedSellingPrice: 1800,
    buyNowPrice: 1800,
    investorPrice: 1530,
    wholesalePrice: 1350,
    acquisitionPrice: 2160,
    minimumOffer: 1260,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 2, favorites: 6 },
    createdAt: '2025-01-15T10:09:00.000Z',
    updatedAt: '2025-01-15T10:09:00.000Z',
  },
  {
    id: 'proj_zxc_sigma',
    name: 'ZXC Sigma Ivory',
    category: 'websites',
    industry: 'Fashion / E-Commerce',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: true,
    overview: 'Drip Again — premium fashion e-commerce storefront deployed on Vercel. Specializes in pre-owned luxury fashion with the tagline "Premium Fashion. Worn Once. Loved Again." Features product catalog, storefront UI, and checkout system built with modern web technologies.',
    businessModel: 'E-Commerce / Fashion Marketplace',
    targetMarket: 'Fashion retailers, luxury resale businesses',
    technologyStack: 'Next.js, React, TypeScript, Vercel',
    tags: 'fashion,ecommerce,storefront,luxury,resale',
    websiteUrl: 'https://zxc-sigma-ivory.vercel.app',
    demoUrl: 'https://zxc-sigma-ivory.vercel.app',
    monthlyVisitors: 750,
    suggestedSellingPrice: 1200,
    buyNowPrice: 1200,
    investorPrice: 1020,
    wholesalePrice: 900,
    acquisitionPrice: 1440,
    minimumOffer: 840,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 1, favorites: 4 },
    createdAt: '2025-01-15T10:10:00.000Z',
    updatedAt: '2025-01-15T10:10:00.000Z',
  },
  {
    id: 'proj_propertyatlas',
    name: 'PropertyAtlas.lifestyle',
    category: 'websites',
    industry: 'Real Estate',
    country: 'Pakistan',
    status: 'active',
    visibility: 'public',
    featured: true,
    overview: 'Luxury real estate lifestyle platform with dark gold-accented UI. Features 10 premium property listings (villas, penthouses, apartments, commercial) across Islamabad neighborhoods with prices from Rs22.5M to Rs320M. Includes real estate agent management (6 agents, 7 user roles), lead pipeline (7 stages, 5 sources with scoring), payment processing (Rs710M+ volume, 5 payment methods), appointment scheduling (4 types), and notification system (8 types). REST APIs for properties, agents, leads, payments, users, and appointments. Built with Next.js, Turbopack, Tailwind CSS v4, shadcn/ui, MongoDB, Playfair Display fonts, and Lucide icons. Contact: +92 331 8333368, playbeatdigital@proton.me, F-7 Markaz Islamabad.',
    businessModel: 'Real Estate Marketplace / SaaS',
    targetMarket: 'Real estate agencies, luxury property buyers, property developers',
    technologyStack: 'Next.js, Turbopack, Tailwind CSS v4, shadcn/ui, MongoDB, Lucide React, Playfair Display',
    tags: 'real-estate,property,luxury,marketplace,agents,leads,payments',
    websiteUrl: 'https://propertyatlas.lifestyle',
    demoUrl: 'https://propertyatlas.lifestyle',
    monthlyVisitors: 2000,
    suggestedSellingPrice: 2600,
    buyNowPrice: 2600,
    investorPrice: 2210,
    wholesalePrice: 1950,
    acquisitionPrice: 3120,
    minimumOffer: 1820,
    sourceCodeAvailable: true,
    auctionEnabled: false,
    sellerId: SELLER.id,
    seller: SELLER,
    _count: { offers: 0, favorites: 0 },
    createdAt: '2025-01-20T10:00:00.000Z',
    updatedAt: '2025-01-20T10:00:00.000Z',
  },
];

/** Find a project by its static ID */
export function findStaticProject(id: string): Project | undefined {
  return STATIC_PRODUCTS.find((p) => p.id === id);
}
